# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Browser.ui'
#
# Created: Mon Oct 21 13:14:32 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from QtExt import QtCore, QtGui, QtWidgets

class Ui_Browser(object):
    def setupUi(self, Browser):
        Browser.setObjectName("Browser")
        Browser.resize(823, 377)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Browser)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createButton = QtWidgets.QToolButton(Browser)
        self.createButton.setMinimumSize(QtCore.QSize(75, 25))
        self.createButton.setMaximumSize(QtCore.QSize(75, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/PNG/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createButton.setIcon(icon)
        self.createButton.setIconSize(QtCore.QSize(22, 22))
        self.createButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout.addWidget(self.createButton)
        self.upLevelButton = QtWidgets.QToolButton(Browser)
        self.upLevelButton.setMinimumSize(QtCore.QSize(25, 25))
        self.upLevelButton.setMaximumSize(QtCore.QSize(25, 25))
        self.upLevelButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/PNG/arrow-up-alt1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upLevelButton.setIcon(icon1)
        self.upLevelButton.setIconSize(QtCore.QSize(16, 16))
        self.upLevelButton.setObjectName("upLevelButton")
        self.horizontalLayout.addWidget(self.upLevelButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Browser)
        self.label.setMinimumSize(QtCore.QSize(69, 25))
        self.label.setMaximumSize(QtCore.QSize(69, 25))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Logo_vektor_grey_foundry24.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.filterLabel = QtWidgets.QLabel(Browser)
        self.filterLabel.setObjectName("filterLabel")
        self.horizontalLayout.addWidget(self.filterLabel)
        self.assetTypeFilterCombo = QtWidgets.QComboBox(Browser)
        self.assetTypeFilterCombo.setObjectName("assetTypeFilterCombo")
        self.horizontalLayout.addWidget(self.assetTypeFilterCombo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bookmarkWidget = QtWidgets.QTableWidget(Browser)
        self.bookmarkWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bookmarkWidget.setGridStyle(QtCore.Qt.NoPen)
        self.bookmarkWidget.setColumnCount(1)
        self.bookmarkWidget.setObjectName("bookmarkWidget")
        self.bookmarkWidget.setColumnCount(1)
        self.bookmarkWidget.setRowCount(0)
        self.bookmarkWidget.horizontalHeader().setVisible(False)
        self.bookmarkWidget.horizontalHeader().setStretchLastSection(True)
        self.bookmarkWidget.verticalHeader().setVisible(False)
        self.bookmarkWidget.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_3.addWidget(self.bookmarkWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(Browser)
        self.pushButton_3.setMinimumSize(QtCore.QSize(25, 20))
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(Browser)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(Browser)
        self.pushButton_2.setMinimumSize(QtCore.QSize(25, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(25, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.mainWidget = QtWidgets.QTableWidget(Browser)
        self.mainWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mainWidget.setGridStyle(QtCore.Qt.NoPen)
        self.mainWidget.setColumnCount(1)
        self.mainWidget.setObjectName("mainWidget")
        self.mainWidget.setColumnCount(1)
        self.mainWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mainWidget.setHorizontalHeaderItem(0, item)
        self.mainWidget.horizontalHeader().setStretchLastSection(True)
        self.mainWidget.verticalHeader().setVisible(False)
        self.mainWidget.verticalHeader().setDefaultSectionSize(25)
        self.horizontalLayout_2.addWidget(self.mainWidget)
        self.versionsWidget = QtWidgets.QTableWidget(Browser)
        self.versionsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.versionsWidget.setGridStyle(QtCore.Qt.NoPen)
        self.versionsWidget.setColumnCount(1)
        self.versionsWidget.setObjectName("versionsWidget")
        self.versionsWidget.setColumnCount(1)
        self.versionsWidget.setRowCount(0)
        self.versionsWidget.horizontalHeader().setVisible(False)
        self.versionsWidget.verticalHeader().setVisible(False)
        self.versionsWidget.verticalHeader().setDefaultSectionSize(25)
        self.horizontalLayout_2.addWidget(self.versionsWidget)
        self.componentsWidget = QtWidgets.QTableWidget(Browser)
        self.componentsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.componentsWidget.setColumnCount(1)
        self.componentsWidget.setObjectName("componentsWidget")
        self.componentsWidget.setColumnCount(1)
        self.componentsWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.componentsWidget.setHorizontalHeaderItem(0, item)
        self.componentsWidget.horizontalHeader().setStretchLastSection(True)
        self.componentsWidget.verticalHeader().setVisible(False)
        self.componentsWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.componentsWidget)
        self.detailsWidget = DetailsWidget(Browser)
        self.detailsWidget.setObjectName("detailsWidget")
        self.horizontalLayout_2.addWidget(self.detailsWidget)
        self.horizontalLayout_2.setStretch(0, 16)
        self.horizontalLayout_2.setStretch(1, 22)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 16)
        self.horizontalLayout_2.setStretch(4, 16)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pathLineEdit = QtWidgets.QLineEdit(Browser)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.verticalLayout.addWidget(self.pathLineEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.assetNameLineEdit = QtWidgets.QLineEdit(Browser)
        self.assetNameLineEdit.setEnabled(False)
        self.assetNameLineEdit.setObjectName("assetNameLineEdit")
        self.horizontalLayout_4.addWidget(self.assetNameLineEdit)
        self.overrideNamehintCheckbox = QtWidgets.QCheckBox(Browser)
        self.overrideNamehintCheckbox.setObjectName("overrideNamehintCheckbox")
        self.horizontalLayout_4.addWidget(self.overrideNamehintCheckbox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Browser)
        QtCore.QObject.connect(self.bookmarkWidget, QtCore.SIGNAL("cellClicked(int,int)"), Browser.bookmarkCellClicked)
        QtCore.QObject.connect(self.mainWidget, QtCore.SIGNAL("cellClicked(int,int)"), Browser.mainCellClicked)
        QtCore.QObject.connect(self.versionsWidget, QtCore.SIGNAL("cellClicked(int,int)"), Browser.versionCellClicked)
        QtCore.QObject.connect(self.upLevelButton, QtCore.SIGNAL("clicked()"), Browser.levelUp)
        QtCore.QObject.connect(self.createButton, QtCore.SIGNAL("clicked()"), Browser.showCreateDialog)
        QtCore.QObject.connect(self.componentsWidget, QtCore.SIGNAL("cellClicked(int,int)"), Browser.componentCellClicked)
        QtCore.QObject.connect(self.overrideNamehintCheckbox, QtCore.SIGNAL("toggled(bool)"), self.assetNameLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Browser)

    def retranslateUi(self, Browser):
        Browser.setWindowTitle(QtWidgets.QApplication.translate("Browser", "Form", None, QtWidgets.QApplication.UnicodeUTF8))
        self.createButton.setText(QtWidgets.QApplication.translate("Browser", "Create", None, QtWidgets.QApplication.UnicodeUTF8))
        self.upLevelButton.setShortcut(QtWidgets.QApplication.translate("Browser", "Ctrl+S", None, QtWidgets.QApplication.UnicodeUTF8))
        self.filterLabel.setText(QtWidgets.QApplication.translate("Browser", "Filter:", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("Browser", "+", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtWidgets.QApplication.translate("Browser", "edit", None, QtWidgets.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("Browser", "-", None, QtWidgets.QApplication.UnicodeUTF8))
        self.versionsWidget.setSortingEnabled(False)
        self.componentsWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Browser", "Components", None, QtWidgets.QApplication.UnicodeUTF8))
        self.overrideNamehintCheckbox.setText(QtWidgets.QApplication.translate("Browser", "Specify Assetname", None, QtWidgets.QApplication.UnicodeUTF8))

from DetailsWidget import DetailsWidget
import ftrackresources_rc
